### ISSUE TITLE
Access MeetupAPI to Pull Information about Our Events

### ISSUE THREAD

**Issue by bestyoucanbe** [nashvillefcc/nashvillefcc2020website#4]
GIVEN that the user wants to see the upcoming Events for our group
WHEN the user clicks on the Our Events link on the Nashville FCC website
THEN the user is presented with detailed information regarding our upcoming events (that is accessed from the Meetups API)

**Comment by JamesMcClarty** [comment]
Awesome. I'll get to work on it as soon as I can.

**Comment by TylerCarpenter92** [comment]
just do some research on it and see if you can get some stuff pulled down using postman or something like it. thanks for responding so fast!

**Comment by JamesMcClarty** [comment]
No problem! I'll see what I can find.

**Comment by JamesMcClarty** [comment]
https://secure.meetup.com/meetup_api/console/

This is a wonderful way to test out Meetup's API. So thoughtful of them!

**Comment by JamesMcClarty** [comment]
Also, we need to make this group an authentic member in order to test in Postman and use it in the site.

**Comment by TylerCarpenter92** [comment]
ya i was talking to laura about that last week. we are thinking there shouldnt be too many fetch requests to go over the free amount. i might just make a quick email to use for that.

**Comment by JamesMcClarty** [comment]
Fair enough!

If we are looking for events based on freeCodeCamp, the best fetch call to do it is:
https://api.meetup.com/freeCodeCamp-Nashville/events

From there, we can add specifications to the way we list our card components on the website.

**Comment by bestyoucanbe** [comment]
@JamesMcClarty  completed a Mockup API for accessing data.  Still need to access the real Meetup information. (FYI -- @Hellrungj )

**Comment by MoribundMedium** [comment]
Rebooting this ticket with #24
