### ISSUE TITLE
Netlify hosting

### ISSUE THREAD

**Issue by MoribundMedium** [nashvillefcc/nashvillefcc2020website#50]
# Acceptance Criteria
Get this site served up over Netlify instead of Github Pages. The build process should be automated and current build files (in /doc folder) should be removed from repo. A document should be introduced detailing our new process

A domain name will need to be acquired at some point, but that is not considered part of the scope of this ticket unless it is needed by Netlify.

### Related Features
- N/A

### Resources
- https://www.netlify.com/with/gatsby/

**Comment by itzsaga** [comment]
Initial setup is complete. See: https://fcc-nashville.netlify.app/
