### ISSUE TITLE
CSS Framework??

### ISSUE THREAD

**Issue by TylerCarpenter92** [nashvillefcc/nashvillefcc2020website#6]
looking for a good fit for the website. We have used reactStrap and react Bootstrap but they feel limited in their use. We would like to see something that is a little more flexible and able to be viewed through a web app on a mobile phone. ie chrome, safari. sass is one good option that I know of but was hoping to see if there was something else that y'all would know of. Laura sent this website to us a few days ago in discord https://tailwindcss.com/. if you guys could try out a few of these and report back to us on what you like and don't like. write in the comments of this issue to report back to us.

**Comment by bestyoucanbe** [comment]
@TylerCarpenter92 @blackcl3 @meltonlogan615 

Logan pointed out the following article as a good read:

https://dev.to/duomly/6-awesome-css-frameworks-which-you-should-know-as-a-front-end-developer-2fbl

**Comment by meltonlogan615** [comment]
I was reading through Bulma and thought it looked like a solid alternative to bootstrap with a pretty simple install, but afterwards it flagged with almost 600 vulnerabilities recently discovered. Soooo, yea, no, not that one.

https://npmjs.com/advisories/1488

**Comment by bestyoucanbe** [comment]
@meltonlogan615 @Hellrungj @lnbailey --- We need to select a CSS framework that we will use going forward.

**Comment by bestyoucanbe** [comment]
After much discussion and weighing the best way forward, I decided to select Tailwind as choice for using CSS with this project.  Logan Melton has already been working hard to get the installation readied for this project.  Some resources for Tailwind that I found online include the following:

Documentation: https://tailwindcss.com/
Best Practices: https://gist.github.com/sandren/0f22e116f01611beab2b1195ab731b63
Online Course: https://tailwindcss.com/course/
GitHub: https://github.com/tailwindcss/tailwindcss
Twitter: https://twitter.com/tailwindcss
Twitter list of community members: https://twitter.com/razorbelle/lists/tailwind-css-community/members

@nashvillefcc/nashvillefcc2020webdevs
