### ISSUE TITLE
Add a 404 Page

### ISSUE THREAD

**Issue by MoribundMedium** [nashvillefcc/nashvillefcc2020website#78]
# Acceptance Criteria
Add a 404 page for incorrect URLs on our site.

A mock-up does not exist just yet!

### Related Features
- N/A

### Design References
Desktop design:
https://xd.adobe.com/view/ae471f35-b465-4155-b95e-4c01bd61deef-fb14/

Mobile design:
https://xd.adobe.com/view/3640d8e0-d80d-43e5-b7d0-fe240a00644f-6313/

**Comment by mariabrock** [comment]
![ErrorPage404-lpatoprobot](https://user-images.githubusercontent.com/54127296/129398077-574059be-7d3c-44f0-b09f-a84b3b40ebb0.png)
![free-404-page-found-vector-redteal](https://user-images.githubusercontent.com/54127296/129398081-ec27e006-c575-48b1-b858-9365e8b40acd.png)
![ErrorPage404-allorange](https://user-images.githubusercontent.com/54127296/129398082-394e3d9f-e73e-498e-a03d-aefd836c48c1.png)


Options for possible 404 image.

**Comment by mariabrock** [comment]
![ErrorPage404-lpatoprobot - 2](https://user-images.githubusercontent.com/54127296/129401197-fe45cc9c-0e81-4dcd-a8cb-b19cf2ef305f.png)
