### ISSUE TITLE
Pointer arrow on hyperlink mouseover isn't changing

### ISSUE THREAD

**Issue by lnbailey** [nashvillefcc/nashvillefcc2020website#86]
**Describe the bug**
The mouse arrow isn't changing to indicate a hyperlink.

**To Reproduce**
1. Go to 'https://www.nashvillefcc.com/'
2. On the home page, scroll down to the events and/or the social media icons.
3. The mouse arrow remains the same. No indication these are hyperlinks.

**Expected behavior**
The indicator should change to a hand or style other than an arrow

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser [Chrome and Safari]

**Smartphone (please complete the following information):**
 - n/a

**Comment by lmpham1** [comment]
This issue seems to have been patched, tested on MacOS/Safari and Windows 10/Chrome and the mouse changed to hand icon

**Comment by Hellrungj** [comment]
> This issue seems to have been patched, tested on MacOS/Safari and Windows 10/Chrome and the mouse changed to hand icon

Thank you for looking into that issue. 👍
