### ISSUE TITLE
 404 Page (Mobile) - Connect SVG image is overlapping with navMenu

### ISSUE THREAD

**Issue by Hellrungj** [nashvillefcc/nashvillefcc2020website#92]
**Describe the bug**
The Connect SVG image is overlapping with navMenu while in the mobile viewport.

**To Reproduce**

#### Mobile:
1. Go to any unlisted route like 'https://www.nashvillefcc.com/404'
2. Click on 'navMenu'
3. See error (Screenshots provide)

-- OR --

#### Desktop:
1. Go to any unlisted route like 'https://www.nashvillefcc.com/404' 
2. Click on 'navMenu'
3. See error (Screenshots provide)

**Expected behavior**
The connect SVG should be in the foreground while the navMenu is active.

**Screenshots**
![Screenshot_20210923-205052_Chrome](https://user-images.githubusercontent.com/8736564/134617120-427edb63-9e0d-4a39-a4ab-ae95cfd4b7cb.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 
**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra 5G
 - OS: Android
 - Browser: Chrome

**Comment by lmpham1** [comment]
I'll give this a try
